name: Automated Builds

on:
  push:
    branches:
      - 'master'

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install C compiler
        uses: rlalik/setup-cpp-compiler@v1.1
        with:
          compiler: clang-latest
        
      - name: Repository checkout
        uses: actions/checkout@v2

      - name: Build binary
        run: make

      - name: Generate tarball
        run: tar zcvf lisp.tar.gz ./lisp init.l

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: lisp_lin
          path: ./lisp.tar.gz

  build_windows:
    runs-on: windows-latest
    steps:
      - name: Install C compiler
        uses: rlalik/setup-cpp-compiler@v1.1
        with:
          compiler: clang-latest

      - name: Repository checkout
        uses: actions/checkout@v2

      - name: Build binary
        run: make
      
      - name: Prepare resources
        run: mv ./lisp ./lisp.exe

      - name: Generate zip
        uses: vimtor/action-zip@v1
        with:
          files: ./lisp.exe init.l
          dest: lisp.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: lisp_win32
          path: ./lisp.zip

  create_release:
    runs-on: ubuntu-latest
    needs: [build_linux, build_windows]
    steps:
      - name: Recover artifacts
        uses: actions/download-artifact@v2

#       - name: Create release
#         id: release_step
#         uses: ncipollo/release-action@v1
#         with:
#           artifacts: "lisp_windows/lisp_windows.zip,lisp_linux/lisp_linux.tar.gz"
#           token: ${{ secrets.GITHUB_TOKEN }}
