name: Automated Builds

on:
  push:
    branches:
      - 'master'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install C compiler
        uses: rlalik/setup-cpp-compiler@v1
        with:
          compiler: clang-latest
      
      - name: Cache compiler
        uses: actions/cache@v2
        
      - name: Repository checkout
        uses: actions/checkout@v2

      - name: Build binary
        run: make release

      - name: Generate tarball
        run: tar zcvf lisp_linux.tar.gz ./lisp init.l

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: lisp_linux
          path: ./lisp_linux.tar.gz

    build-windows:
      runs-on: windows-latest
      steps:
        - name: Install C compiler
          uses: rlalik/setup-cpp-compiler@v1
          with:
            compiler: clang-latest

        - name: Cache compiler
          uses: actions/cache@v2

        - name: Repository checkout
          uses: actions/checkout@v2

        - name: Build binary
          run: make release

        - name: Generate zip
          uses: vimtor/action-zip@v1
          with:
            files: |
              ./lisp.exe
              init.l
            dest: lisp_windows.zip

        - name: Upload artifacts
          uses: actions/upload-artifact@v2
          with:
            name: lisp_windows
            path: ./lisp_windows.zip

    create-release:
      runs-on: ubuntu-latest
      needs: [build-linux, build-windows]
      steps:
        - name: Recover artifacts
          uses: actions/download-artifact@v2
          
        - name: Create release
          id: release_step
          uses: ncipollo/release-action@v1
          with:
            artifacts: "lisp_windows/lisp_windows.zip,lisp_linux/lisp_linux.tar.gz"
            token: ${{ secrets.GITHUB_TOKEN }}

